### ISSUE TITLE
句子轉漢語發音的功能編寫

### ISSUE THREAD

**Issue by Evanston0624** [p208p2002/py-chinese-pronounce#2]
請參考我自己複製的版本:
https://github.com/Evanston0624/word-to-phoneme/blob/main/py_chinese_pronounce/core.py

上述的.py 檔內的 def sent_to_han 是我編寫的字串轉發音。

我嘗試編寫了句子轉漢語發音的function

上述的.py檔內的function : sent_to_han

"sent_to_han" 是基於"sent_to_chewin"，將句子參考dict_concised_2014_20230112.xlsx轉為注音

在逐個注音透過"_chewin2han"轉為漢語拼音

但當今天輸入的句子包含多音詞時會存在某些邏輯上的錯誤(不好、本事)
![圖片](https://github.com/p208p2002/py-chinese-pronounce/assets/48548555/9617f835-49c6-41dd-89d4-379524fdbf47)

因此在sent_to_han包含一個多音詞的判斷式，會選擇dict_concised_2014_20230112.xlsx內多音排序最小的詞發音。

如果有空閒的話想請教你們是否有重新編寫字串轉發音的function，或是我編寫的有沒有存在什麼漏洞?

感謝你們的貢獻，有任何問題或意見都歡迎回復，謝謝。

**Comment by p208p2002** [comment]
感謝您的建議與實作! 我會抽空確認這個作法是否合適

**Comment by p208p2002** [comment]
@Evanston0624 看起來沒什麼問題， 我已經將你的程式碼整合，並且新增`sent_to_han`。再次感謝協助!

**Comment by Evanston0624** [comment]
不客氣

Best Regards.
*HY. Su*

------------------------------------------------------------

Phone : +886-963-689-636
Email : ***@***.***


Philip ***@***.***> 於 2023年10月26日 週四 下午4:38寫道：
